# Generated by Django 3.0 on 2019-12-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('package_destination', models.CharField(max_length=50)),
                ('package_sizes', models.CharField(max_length=50)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strona.PackageType')),
            ],
            options={
                'ordering': ['create_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveredPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('delivered_date', models.DateTimeField(auto_now_add=True)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strona.PackageType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
