# Generated by Django 3.0 on 2019-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_oldchange_packagechange_removedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldchange',
            name='package_destination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oldchange',
            name='package_sizes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packagechange',
            name='package_destination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packagechange',
            name='package_sizes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
