# Generated by Django 3.0 on 2020-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0005_auto_20200107_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldchange',
            name='package_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packagechange',
            name='package_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
