# Generated by Django 3.0 on 2020-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_auto_20200107_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NDY', 'Not Deposited Yet'), ('DP', 'Depository'), ('IT', 'In Transit'), ('DE', 'Delivering')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
