# Generated by Django 3.0 on 2020-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NDY', 'Not Deposited Yet'), ('DP', 'Depository'), ('IT', 'In Transit'), ('DE', 'Delivering')], default='NDY', max_length=3),
        ),
    ]
