# Generated by Django 3.0.2 on 2020-01-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_auto_20200109_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldchange',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='packagechange',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
