# Generated by Django 3.0.2 on 2020-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0010_auto_20200109_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveredpackage',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='removedpackage',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
