# Generated by Django 3.0.2 on 2020-01-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0012_addingstats_deletingstats_deliveringstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddingStats',
        ),
        migrations.DeleteModel(
            name='DeletingStats',
        ),
        migrations.DeleteModel(
            name='DeliveringStats',
        ),
    ]
