# Generated by Django 3.0.2 on 2020-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_auto_20200110_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingstats',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deletingstats',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveringstats',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
