# Generated by Django 3.0.2 on 2020-01-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0016_auto_20200110_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addingstats',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='deletingstats',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='deliveringstats',
            options={'ordering': ['date']},
        ),
    ]
